### ISSUE TITLE
Terminate does not clean up timer

### ISSUE THREAD

**Issue by Umaaz** [intergral/java-adonis-websocket#1]
A timer is created to handle ping messages, however if you call 'terminate' then the timer is not destroyed so the next time the timer runs you get a NPE.

```
java.lang.NullPointerException
	at com.nerdvision.adonis.AdonisWebSocketClient.sendMessage(AdonisWebSocketClient.java:263)
	at com.nerdvision.adonis.AdonisWebSocketClient.access$300(AdonisWebSocketClient.java:41)
	at com.nerdvision.adonis.AdonisWebSocketClient$1.run(AdonisWebSocketClient.java:301)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```

**Comment by Umaaz** [comment]
resolved in 0.0.2
